version: '3.1'

services:
    db:
        build:
            context: ./mysql/.
        image: duze_db
        container_name: duze_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            # MYSQL_USER: "${MYSQL_USER}"
            # MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
            LANG: C.UTF-8
        restart: always
        volumes:
            - /tmp:/tmp

    backend:
        build:
            context: ..
            dockerfile: ./docker/java/Dockerfile
        image: duze_backend
        container_name: duze_backend
        ports:
            - "8080:8080"
        environment:
            SPRING_DATABASE_URL: "jdbc:mysql://db:3306/kino"
            SPRING_DATABASE_USERNAME: "${MYSQL_USERNAME}"
            SPRING_DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
            SPRING_PROFILES_ACTIVE: "prod"
        depends_on:
            - db

    frontend:
        build:
            context: ..
            dockerfile: ./docker/js/Dockerfile
            args:
                NGINX_CONFIG_PATH: ./docker/js/nginx.conf
        image: duze_frontend
        container_name: duze_frontend
        ports:
            - "80:63342"