version: '3.1'

services:
    db:
        build:
            context: ./mysql/.
        image: duze_db
        container_name: duze_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            # MYSQL_USER: "${MYSQL_USER}"
            # MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
            LANG: C.UTF-8
        restart: always
        volumes:
            - /tmp:/tmp

    backend:
        build:
            context: ..
            dockerfile: ./docker/java/Dockerfile
            args:
                JAR: "DuzeKino-0.0.1-SNAPSHOT.jar"
        image: duze_backend
        container_name: duze_backend
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/Kino"
            SPRING_DATASOURCE_USERNAME: "${MYSQL_USERNAME}"
            SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
        depends_on:
            - db

#    frontend:
#        build:
#            context: ./js/.
#        image: duze_frontend
#        container_name: duze_frontend
#        ports:
#            - "63342:63342"